// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://tburuwpllmvrijxapxmg.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRidXJ1d3BsbG12cmlqeGFweG1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzIxODgzNDMsImV4cCI6MjA0Nzc2NDM0M30._ykIEaf-JRjduFuUbToCvvA11vOiS5KokjGyxeZc-q0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);